### ISSUE TITLE
Crash upon converting .it module

### ISSUE THREAD

**Issue by vince94** [tewtal/mITroid#1]
This module was created with mukunda's snesmod tool in mind, but I just thought I'd try converting it. Upon clicking the Save SPC button, it gives this error message: https://pastebin.com/raw/wSTCXhyf

Here's a [link](https://cdn.discordapp.com/attachments/321488771747020804/409759702944317461/Welcoming_Wind.it) to the module. (It's a SNES-style demake of [this track](https://www.youtube.com/watch?v=rYDIUHCtZrw) from Final Fantasy Dimensions)
Also, I just want to say thank you for starting this project! I've used [snesmod](https://youtu.be/r0zQU5ARtX0?t=11) and the [EarthBound Music Editor](https://youtu.be/YThDgDt7Ozg) to great effect, but they all have specific limitations (snesmod having slightly finicky brr conversion, and EBMusEd not supporting custom BRR samples). This looks really promising and I'm excited to use it in the future!

**Comment by tewtal** [comment]
I took a look at it quickly and it seems like the issue was running out of sample space. Right now it's very limited due to the fact that the program is made with the limitations of being able to insert the music data and samples into Super Metroid without affecting any sound effects or other music data.

I'm planning to add an option though to just overwrite all of that if the goal is to just create an SPC file. That'll give more space for pattern data and samples since there's no worries about ever trying to put it back into a game.

Your file helped me find and fix another bug though related to effect memory for vibrato and some other effects so that was really helpful :)

**Comment by tewtal** [comment]
I've finally gotten around to implementing support for "overwrite everything and give me all the space". So now it's possible to create more complex music with more samples when creating music just for SPC-replay or for something like credits music in a game where it doesn't matter if all the old samples and data gets overwritten. Hopefully the tool can be a bit more useful now for just making music without any specific game in mind.
